services:
  postgresql:
    image: postgres:16
    container_name: postgresqlsp
    environment:
      - POSTGRES_USER=${SPPOSTGRES_USER}
      - POSTGRES_PASSWORD=${SPPOSTGRES_PASSWORD}
      - POSTGRES_DB=${SPPOSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_sp:/var/lib/postgresql/data
      - ./scripts-schemaprocessor:/docker-entrypoint-initdb.d
    networks:
      - sp_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
      PGADMIN_LISTEN_PORT: 5051
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1 # Important for Codespaces
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1 # Important for Codespaces
    volumes:
      - pgadmin_datasp:/var/lib/pgadmin
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-config/config_local.py:/var/lib/pgadmin/config_local.py:ro
    networks:
      - sp_network
    depends_on:
      postgresql:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5051:8080"
    volumes:
      - ./backend/src/schemaprocessor/nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - sp_network
    depends_on:
      pgadmin:


volumes:
  postgres_datasp:
  pgadmin_datasp:

networks:
  sp_network:
    driver: bridge
